# Generated by Django 2.2.3 on 2020-03-20 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerhq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='GameImage',
            field=models.CharField(default='', max_length=128),
        ),
    ]
