# Generated by Django 2.2.3 on 2020-03-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerhq', '0003_auto_20200320_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='GameImage',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
