# Generated by Django 2.2.3 on 2020-03-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerhq', '0005_auto_20200320_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='GameImage',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='GameImage',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
